import Head from 'next/head'
import './globals.css'
import { Poppins } from 'next/font/google'

const poppins = Poppins({weight: ['100', '200', '300', '400', '500', '600', '700', '800',], subsets: ['devanagari']})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <Head>
      <meta name="viewport" content="width=device-width,initial-scale=1, maximum-scale=1" />

      </Head>
      <body className={poppins.className}>{children}</body>
    </html>
  )
}
