import Head from 'next/head'
import './globals.css'
import { Poppins } from 'next/font/google'
import { Noto_Sans_Georgian } from 'next/font/google'
import { Lato } from 'next/font/google'
import { Providers } from '@/redux/Provider'

const poppins = Poppins({weight: ['100', '200', '300', '400', '500', '600', '700', '800',], subsets: ['devanagari']})
const georgian = Noto_Sans_Georgian({subsets: ['georgian']})
const lato = Lato({ subsets: ['latin-ext'],
  weight: ['100', '300', '400', '700', '900'],
  style: 'normal'})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
       <head>
      <meta name="viewport" content="width=device-width,initial-scale=1, maximum-scale=1" />
    <link rel="preconnect" href="https://fonts.googleapis.com"/>
    <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin= 'use-credentials'/>
    <link href="https://fonts.googleapis.com/css2?family=Lato:ital,wght@0,100;0,300;0,400;0,700;0,900;1,100;1,300;1,400;1,700;1,900&family=Raleway:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;1,200;1,300;1,400;1,500;1,600;1,700;1,800&display=swap" rel="stylesheet"/>  
         </head>
      <body className={lato.className}>
       <Providers>{children}</Providers>
      </body>
    </html>
  )
}
