import Head from 'next/head'
import './globals.css'
import { Poppins } from 'next/font/google'

const poppins = Poppins({weight: ['100', '200', '300', '400', '500', '600', '700', '800',], subsets: ['devanagari']})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
       <head>
      <meta name="viewport" content="width=device-width,initial-scale=1, maximum-scale=1" />
      <link rel="preconnect" href="https://fonts.googleapis.com"/>
    <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin=''/>
    <link href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,400;0,500;0,600;0,700;0,800;1,400;1,500;1,600;1,700&display=swap" rel="stylesheet"/>
      </head>
      <body>{children}</body>
    </html>
  )
}
